### PR TITLE
Script to create new `chain_campaign`

### LINKED ISSUE #13: Create new chain campaigns based on those that have some desired campaign included in their chain.
Create new chain campaigns based on those that have some campaign included in the chain

This is related to the development of elements 4 and 6 described in the following ticket: [PDMVMCPROD-98](https://its.cern.ch/jira/browse/PDMVMCPROD-98).

### Describe the solution you'd like

Given a McM query, scan all the `chain_campaign` which includes one specific campaign into their chain, and replace part of its chain with new campaigns and flows given as input. After this, submit this transaction to McM to create the new `chain_campaign` based on this modification.

## Additional context

Currently, the development environment uses the new SSO, users who have 2FA enabled will face issues as described in #8. Please use the credentials, and Kerberos authentication, related to an account that doesn’t have this enabled in the meantime this issue is closed.

### PR DESCRIPTION
**Pull request by ggonzr**
Let's discuss this version and its output as a first iteration

### CODE REVIEW

**Comment by ggonzr** [comment]
Hi team,

This script is the first iteration to complete the requirement described in the linked issue and the JIRA ticket (Thanks @jordan-martins for the reference script to develop this one). Please can you check the following output before proceeding to create the `chain_campaigns` in the development environment.

Output: [execution.log](https://github.com/cms-PdmV/mcm_scripts/files/12619938/execution.log)

FYI: @jordan-martins, @sunilUIET, @miquork

Thanks,
Geovanny

**Comment by sunilUIET** [comment]
Hi @ggonzr 

Thanks for the efforts! From execution.log it appears that everything on the expected line. One addition, can you please change flag  'do_not_check_cmssw_versions':  --> True for chain_campaign.

**Comment by ggonzr** [comment]
Hi @sunilUIET,

I set the attribute to the requested value. Please let me know if there are other changes required or if we can proceed to test this in the development environment.

Best,
Geovanny

**Comment by sunilUIET** [comment]
Hi @ggonzr 

Let's test it in the development env. 

Regards
Sunil

**Comment by ggonzr** [comment]
Hi @sunilUIET,

They are now created in the development environment. I am including the logs related to this process: [execution_2023_09_18_10_50.log](https://github.com/cms-PdmV/mcm_scripts/files/12646299/execution_2023_09_18_10_50.log). Next, I list the created chain campaigns which include the new campaigns and flows:

1. [Run3Summer22MiniAODv4](https://cms-pdmv-dev.web.cern.ch/mcm/chained_campaigns?contains=Run3Summer22MiniAODv4&page=0&shown=15)
2. [Run3Summer22EEMiniAODv4](https://cms-pdmv-dev.web.cern.ch/mcm/chained_campaigns?contains=Run3Summer22EEMiniAODv4&page=0&shown=15)
3. [Run3Summer22NanoAODv12](https://cms-pdmv-dev.web.cern.ch/mcm/chained_campaigns?contains=Run3Summer22NanoAODv12&page=0&shown=15)
4. [Run3Summer22EENanoAODv12](https://cms-pdmv-dev.web.cern.ch/mcm/chained_campaigns?contains=Run3Summer22EENanoAODv12&page=0&shown=15)

Some highlights: Some chain campaigns existed before submitting this transaction (127 in total). How should we proceed with them? Should we ‘force update’ them? To list them, search the prompt “'results': False” for more details

Best,
Geovanny

**Comment by sunilUIET** [comment]
Thanks @ggonzr
At first look, these look fine. I created those chain_campaigns but can be force updated.

**Comment by ggonzr** [comment]
Hi team,

The last commit includes the ticket creation (element 6 described in the JIRA ticket) in McM. I am attaching the execution output: [execution_2023_09_19_19_44.log](https://github.com/cms-PdmV/mcm_scripts/files/12665003/execution_2023_09_19_19_44.log). These new chain campaigns and tickets are available in McM development environment, please check them and the last commit and let me know if there are changes to perform.

FYI: @jordan-martins, @sunilUIET, @miquork

Best,
Geovanny

**Comment by ggonzr** [comment]
There was an issue with the data used to create the ticket in the transaction (Please see the last commit for more details). I have performed another test and the output was: [execution_2023_09_20_16_14.log](https://github.com/cms-PdmV/mcm_scripts/files/12674145/execution_2023_09_20_16_14.log). You can find all the tickets in the following link: [Tickets](https://cms-pdmv-dev.web.cern.ch/mcm/mccms?prepid=PPD-2023Sep20-*&page=1&shown=127).

Best regards,
Geovanny

**Comment by ggonzr** [comment]
The last commit operates the ticket. The new tickets and their `chain_requests` are available at: [New Test](https://cms-pdmv-dev.web.cern.ch/mcm/mccms?prepid=PPD-2023Sep27-*&page=1&shown=65535). For some reason, the `chain_requests` are created but they include no request into them. Please can you check them and the currently available source code and let me know why this behavior happens?

Execution log: [execution_2023_09_21_19_02.log](https://github.com/cms-PdmV/mcm_scripts/files/12689337/execution_2023_09_21_19_02.log)

Thanks,
Geovanny

**Comment by ggonzr** [comment]
I think we’re almost done with this task. The last version of the script is able to reserve the chain and update the total of events. So, this solves element 6 for the JIRA ticket. Unfortunately, it could be possible that the web server fails due to server load or timeouts. For this test, one ticket failed on reserving the `chain_requests`, I think we can fix these issues later by manually resetting the ticket and processing it again. 

The newly created tickets are available at [New tickets](https://cms-pdmv-dev.web.cern.ch/mcm/mccms?prepid=PPD-2023Sep27-*&page=1&shown=32767). Please check its data and let me know if there are issues.

Execution log: [execution_2023_09_22_15_56.log](https://github.com/cms-PdmV/mcm_scripts/files/12701709/execution_2023_09_22_15_56.log)

FYI: @jordan-martins, @sunilUIET, @miquork

Thanks,
Best regards,
Geovanny

**Comment by ggonzr** [comment]
I included some changes to avoid skipping `chain_campaign` and to modify the execution order to increase the fault tolerance for the process. Please can you check the following output and these [tickets](https://cms-pdmv-dev.web.cern.ch/mcm/mccms?prepid=PPD-2023Sep27-*&page=1&shown=32767) and let me know if we can proceed to execute this process in production

Execution output: [execution_2023_09_25.log](https://github.com/cms-PdmV/mcm_scripts/files/12725889/execution_2023_09_25.log)

Best,
Geovanny

**Comment by ggonzr** [comment]
Even if we skip some `chain_campaign` and `root_request` which are not of interest, the total number of events for this ticket creation process is the same: **22,486,047,357**. In theory, as discussed yesterday, the total number should be around: **20,500,000,000** (20.5B events following the US numeric system).

New tickets are available at: [Tickets](https://cms-pdmv-dev.web.cern.ch/mcm/mccms?prepid=PPD-2023Sep27-*&page=1&shown=32767) – From `PPD-2023Sep27-00362` to `PPD-2023Sep27-00489`

Execution log: [execution_2023_09_26.log](https://github.com/cms-PdmV/mcm_scripts/files/12736166/execution_2023_09_26.log)

Jordan (@jordan-martins) please can you check the log and suggest why this behavior happens

Thanks,
Geovanny

**Review by jordan-martins — APPROVED** [review]
Everything is fine as requested :)

**Pull request merged**
